sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install

script:
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run -v .
  - ./vendor/bin/psalm --show-info=false --no-progress
  - ./vendor/bin/phpunit